# Force internal session to be screen-256color
set -g default-terminal "screen-256color"

# Tell tmux that "xterm" supports 256 colors and TrueColor (Tc)
set -ga terminal-overrides ",*xterm*:colors=256:Tc"
