set -g default-terminal "screen-256color"
# This forces Tmux to send Italics (\E[3m) and TrueColor (Tc) 
# to the outer terminal, regardless of what terminfo says.
set -g terminal-overrides ",*xterm*:Tc:sitm=\E[3m:ritm=\E[23m,smso=\E[7m"
