# 0 is too far from ` ;)
set -g base-index 1

# Automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on

set -g history-limit 10000
setw -g monitor-activity on

# Auto resize to smallest connected client
setw -g aggressive-resize on

# This gets truecolor and italics right in tmux in gnome terminal:
# 1) Make a file called `st-256color-italic.terminfo`
# 2) Give it the following content (ignore up to '>'):
#    > st-256color-italic|st with 256 colors and italic,
#    >         sitm=\E[3m, ritm=\E[23m,
#    >         use=st-256color,
# 3) Run the command:
#    > tic -v10 -o "." st-256color-italic.terminfo
# 4) A directory called 's' will be created in the cwd, in that directory is a
#    file called st-256color-italic. Copy this file to:
#    `/usr/share/terminfo/s/st-256color-italic`
# 5) Set the following `~/.tmux.conf`:
#    > set -g default-terminal "st-256color-italic"
#    > set -ga terminal-overrides ",st-256color:Tc"

set -g default-terminal "st-256color-italic"
set -ga terminal-overrides ",st-256color:Tc"

# Vim keybindings
set -g status-keys vi
setw -g mode-keys vi

bind-key v split-window -h
bind-key s split-window -v

bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key H resize-pane -L 5
bind-key L resize-pane -R 5

bind-key M-j resize-pane -D
bind-key M-k resize-pane -U
bind-key M-h resize-pane -L
bind-key M-l resize-pane -R

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Copy tmux selection to system clipboard
# (works for xorg, not for wayland or tty session, must have xclip installed)
# 1. Press CTRL-B [
# 2. Move to text you want to copy
# 3. Press space to mark a selection
# 4. Press press y to copy the selection to your systems clipboard
# ( or press Enter to copy it to tmux clipboard )
bind -t vi-copy y copy-pipe 'xclip -in -selection clipboard'

# No delay for escape key press
set -sg escape-time 0

# Reload tmux config
bind r source-file ~/.tmux.conf

# Theme settings
set -g pane-border-fg black
set -g pane-active-border-fg green
set -g pane-active-border-bg default
set -g status-bg '#121212'
set -g status-fg white
set -g window-status-current-bg '#444444'
set -g window-status-current-fg white
set -g window-status-current-attr bold
set -g status-interval 60
set -g status-left-length 30
set -g status-left  '#[fg=#AFD787, bg=#121212](#S) #(whoami) #[default] '
set -g status-right '#[fg=#AFD787, bg=#121212] %H:%M '

